export const horizons = ['inbox', 'now', 'next', 'soon', 'later', 'someday', 'waiting', 'reference'] as const;
export type Horizon = typeof horizons[number];
export type Task = { id: string; title: string; notes: string; horizon: Horizon; project: string; people: string[]; places: string[]; due: string; minutes: number; energy: string; completed: boolean; deleted?: boolean; createdAt: string; updatedAt: string; version: number; };
export const labels: Record<string, string> = { inbox: 'Inbox', now: '1-Now', next: '2-Next', soon: '3-Soon', later: '4-Later', someday: '5-Someday', waiting: 'Waiting', reference: 'Cabinet', completed: 'Completed', all: 'All actions', review: 'Weekly review' };
export function makeTask(title: string, horizon: Horizon = 'inbox'): Task { return { id: crypto.randomUUID(), title, horizon, notes: '', project: '', people: [], places: [], due: '', minutes: 0, energy: '', completed: false, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), version: 1 }; }
export function exampleTasks(): Task[] {
  const base = (id: string, title: string, horizon: Horizon, project: string, places: string[], minutes: number, notes: string): Task => ({ id, title, horizon, project, places, minutes, notes, people: [], due: '', energy: '', completed: false, createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z', version: 1 });
  return [base('example-1', 'Choose the next step for a project', 'now', 'A meaningful project', ['Computer'], 15, 'Write a small, visible action you can actually finish.'), { ...base('example-2', 'Ask Alex for feedback on the outline', 'now', 'A meaningful project', ['Work'], 10, 'Keep meeting notes and the action they support in one place.'), people: ['Alex'] }, base('example-3', 'Make a list for the next grocery trip', 'now', 'Personal', ['Home'], 5, 'Try choosing Home in the context filter to narrow this list.'), base('example-4', 'A thought you haven’t organized yet', 'inbox', '', [], 0, 'Capture first. Decide what to do about it later.'), base('example-5', 'Sketch the first draft', 'next', 'A meaningful project', ['Computer'], 30, ''), base('example-6', 'Plan a weekend away', 'someday', 'Personal', [], 0, '')];
}
